# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mark Kennedy
email: markkennedy@umail.ucc.ie
description: > # this means to ignore newlines until "baseurl:"
  Mark Kennedy is a PhD student in the field of astrophysics, working between the University College Cork and University of Notre Dame. Primary interests are catalcysmic variables and interacting binaries.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: markrtkennedy
github_username:  mkenne15

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title
