# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dr. Mark Kennedy
email: markkennedy@ucc.ie
description: > # this means to ignore newlines until "baseurl:"
 I've just started a Postdoctoral fellowship at UCC to look for quiescent black holes in wide-field optical surveys. I'm also interested in irradiated pulsar binaries and cataclysmic variables.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mkenne15.github.io" # the base hostname & protocol for your site
twitter_username: markrtkennedy
github_username:  mkenne15
google_scholar_username: Mark Kennedy
linkedin_username: markrtkennedy
arxiv_username: ArXiv

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title
